# post destination info
[settings]
instance = "lemmy.world"
community = "memes"
username_or_email = "test@example.com"
password = "password"
enabled = false


# defaults for omitted post fields
[defaults]
title = "Today's secret word"

# can use template strings to customize per post
body = "Today's secret word is: {secret}"

# don't need to specify all of them
#link = ""
#thumbnail = ""
#alt_text = ""


# a regular post
[[post]]
post_at = "2024-10-04 14:00:00-0700"
title = "What's today's secret?"
body = "I never find out about these things."


# a post that fills out the default body with a value
[[post]]
post_at = "2024-10-04 15:00:00-0700"
secret = "banana"
